package theme

// Default is the palette used when nothing else is chosen: the text carries the
// interface, with a single accent reserved for live figures.
const Default = "mono"

var registry = map[string]Theme{
	"mono": {
		Name: "mono", Desc: "dim gray, one cyan accent",
		Pending:   Style{FG: "#4c4f5a"},
		Correct:   Style{FG: "#e6e6ea"},
		Incorrect: Style{FG: "#e05561"},
		Extra:     Style{FG: "#7c3b42"},
		Missed:    Style{FG: "#8c4a50"},
		Text:      Style{FG: "#c8ccd4"},
		Dim:       Style{FG: "#5c6370"},
		Accent:    Style{FG: "#56b6c2"},
		Racers:    [6]Colour{"#c678dd", "#e5c07b", "#98c379", "#61afef", "#d19a66", "#f0a8d0"},
	},
	"amber": {
		Name: "amber", Desc: "cream on dark, amber accent",
		Pending:   Style{FG: "#6b5836"},
		Correct:   Style{FG: "#f2e0b6"},
		Incorrect: Style{FG: "#d9534f"},
		Extra:     Style{FG: "#7a4430"},
		Missed:    Style{FG: "#96513c"},
		Text:      Style{FG: "#e6cfa0"},
		Dim:       Style{FG: "#8a7550"},
		Accent:    Style{FG: "#f0a500"},
		Racers:    [6]Colour{"#8fbf7f", "#7fa7d9", "#d98fb3", "#c9b458", "#b39ddb", "#6fc2c2"},
	},
	"neon": {
		Name: "neon", Desc: "cyan and magenta",
		Pending:   Style{FG: "#454a5e"},
		Correct:   Style{FG: "#e8e8f4"},
		Incorrect: Style{FG: "#ff5f87"},
		Extra:     Style{FG: "#7a3050"},
		Missed:    Style{FG: "#9c3d63"},
		Text:      Style{FG: "#d0d0e0"},
		Dim:       Style{FG: "#6a6a8a"},
		Accent:    Style{FG: "#00d7ff"},
		Racers:    [6]Colour{"#ff5fd7", "#afff5f", "#ffd75f", "#af87ff", "#5fffaf", "#ff875f"},
	},
	"terminal": {
		Name: "terminal", Desc: "inherits your terminal colours",
		Pending:   Style{FG: "ansi:8"},
		Correct:   Style{FG: "ansi:15"},
		Incorrect: Style{FG: "ansi:1"},
		Extra:     Style{FG: "ansi:1", Faint: true},
		Missed:    Style{FG: "ansi:9", Faint: true},
		Text:      Style{FG: "ansi:7"},
		Dim:       Style{FG: "ansi:8"},
		Accent:    Style{FG: "ansi:6"},
		Racers:    [6]Colour{"ansi:5", "ansi:2", "ansi:3", "ansi:4", "ansi:13", "ansi:10"},
	},
	"catppuccin": {
		Name: "catppuccin", Desc: "mocha",
		Pending:   Style{FG: "#585b70"},
		Correct:   Style{FG: "#cdd6f4"},
		Incorrect: Style{FG: "#f38ba8"},
		Extra:     Style{FG: "#7d3f52"},
		Missed:    Style{FG: "#eba0ac"},
		Text:      Style{FG: "#bac2de"},
		Dim:       Style{FG: "#6c7086"},
		Accent:    Style{FG: "#cba6f7"},
		Racers:    [6]Colour{"#89b4fa", "#a6e3a1", "#f9e2af", "#fab387", "#94e2d5", "#f5c2e7"},
	},
	"gruvbox": {
		Name: "gruvbox", Desc: "dark medium",
		Pending:   Style{FG: "#665c54"},
		Correct:   Style{FG: "#ebdbb2"},
		Incorrect: Style{FG: "#fb4934"},
		Extra:     Style{FG: "#9d0006"},
		Missed:    Style{FG: "#cc241d"},
		Text:      Style{FG: "#d5c4a1"},
		Dim:       Style{FG: "#7c6f64"},
		Accent:    Style{FG: "#fabd2f"},
		Racers:    [6]Colour{"#83a598", "#b8bb26", "#d3869b", "#8ec07c", "#fe8019", "#458588"},
	},
	"nord": {
		Name: "nord", Desc: "arctic, north bluish",
		Pending:   Style{FG: "#4c566a"},
		Correct:   Style{FG: "#eceff4"},
		Incorrect: Style{FG: "#bf616a"},
		Extra:     Style{FG: "#6d383e"},
		Missed:    Style{FG: "#a3545c"},
		Text:      Style{FG: "#d8dee9"},
		Dim:       Style{FG: "#616e88"},
		Accent:    Style{FG: "#88c0d0"},
		Racers:    [6]Colour{"#b48ead", "#a3be8c", "#ebcb8b", "#81a1c1", "#d08770", "#8fbcbb"},
	},
	"dracula": {
		Name: "dracula", Desc: "classic dracula",
		Pending:   Style{FG: "#6272a4"},
		Correct:   Style{FG: "#f8f8f2"},
		Incorrect: Style{FG: "#ff5555"},
		Extra:     Style{FG: "#7a2a2a"},
		Missed:    Style{FG: "#c04545"},
		Text:      Style{FG: "#e2e2dc"},
		Dim:       Style{FG: "#6272a4"},
		Accent:    Style{FG: "#bd93f9"},
		Racers:    [6]Colour{"#ff79c6", "#50fa7b", "#f1fa8c", "#8be9fd", "#ffb86c", "#a4ffff"},
	},
	"tokyonight": {
		Name: "tokyonight", Desc: "night",
		Pending:   Style{FG: "#414868"},
		Correct:   Style{FG: "#c0caf5"},
		Incorrect: Style{FG: "#f7768e"},
		Extra:     Style{FG: "#7a3b4a"},
		Missed:    Style{FG: "#b4526a"},
		Text:      Style{FG: "#a9b1d6"},
		Dim:       Style{FG: "#565f89"},
		Accent:    Style{FG: "#7aa2f7"},
		Racers:    [6]Colour{"#bb9af7", "#9ece6a", "#e0af68", "#7dcfff", "#ff9e64", "#73daca"},
	},
	"rosepine": {
		Name: "rosepine", Desc: "soho vibes",
		Pending:   Style{FG: "#6e6a86"},
		Correct:   Style{FG: "#e0def4"},
		Incorrect: Style{FG: "#eb6f92"},
		Extra:     Style{FG: "#7a3d4f"},
		Missed:    Style{FG: "#b4637a"},
		Text:      Style{FG: "#c5c3ce"},
		Dim:       Style{FG: "#6e6a86"},
		Accent:    Style{FG: "#9ccfd8"},
		Racers:    [6]Colour{"#c4a7e7", "#f6c177", "#ebbcba", "#3e8fb0", "#56949f", "#d7827e"},
	},
}
